doing/config/routes.rb
Rails.application.routes.draw do
  resources :doing_items

end

doing/app/models/doing_item.rb
class DoingItem < ActiveRecord::Base
end

doing/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

doing/app/controllers/doing_items_controller.rb
class DoingItemsController < ApplicationController
  before_action :set_doing_item, only: [:show, :edit, :update, :destroy]

  # GET /doing_items
  # GET /doing_items.json
  def index
    @doing_items = DoingItem.all
  end

  # GET /doing_items/1
  # GET /doing_items/1.json
  def show
  end

  # GET /doing_items/new
  def new
    @doing_item = DoingItem.new
  end

  # GET /doing_items/1/edit
  def edit
  end

  # POST /doing_items
  # POST /doing_items.json
  def create
    @doing_item = DoingItem.new(doing_item_params)

    respond_to do |format|
      if @doing_item.save
        format.html { redirect_to @doing_item, notice: 'Doing item was successfully created.' }
        format.json { render :show, status: :created, location: @doing_item }
      else
        format.html { render :new }
        format.json { render json: @doing_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doing_items/1
  # PATCH/PUT /doing_items/1.json
  def update
    respond_to do |format|
      if @doing_item.update(doing_item_params)
        format.html { redirect_to @doing_item, notice: 'Doing item was successfully updated.' }
        format.json { render :show, status: :ok, location: @doing_item }
      else
        format.html { render :edit }
        format.json { render json: @doing_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doing_items/1
  # DELETE /doing_items/1.json
  def destroy
    @doing_item.destroy
    respond_to do |format|
      format.html { redirect_to doing_items_url, notice: 'Doing item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doing_item
      @doing_item = DoingItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doing_item_params
      params.require(:doing_item).permit(:title, :deadline, :priority, :complete, :description)
    end
end

doing/app/helpers/application_helper.rb
module ApplicationHelper
end

doing/app/helpers/doing_items_helper.rb
module DoingItemsHelper
end

doing/app/views/doing_items/_form.html.erb
<%= form_for(@doing_item) do |f| %>
  <% if @doing_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doing_item.errors.count, "error") %> prohibited this doing_item from being saved:</h2>

      <ul>
      <% @doing_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.datetime_select :deadline %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <%= f.number_field :priority %>
  </div>
  <div class="field">
    <%= f.label :complete %><br>
    <%= f.check_box :complete %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

doing/app/views/doing_items/edit.html.erb
<h1>Editing Doing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @doing_item %> |
<%= link_to 'Back', doing_items_path %>

doing/app/views/doing_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Doing Items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Deadline</th>
      <th>Priority</th>
      <th>Complete</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doing_items.each do |doing_item| %>
      <tr>
        <td><%= doing_item.title %></td>
        <td><%= doing_item.deadline %></td>
        <td><%= doing_item.priority %></td>
        <td><%= doing_item.complete %></td>
        <td><%= doing_item.description %></td>
        <td><%= link_to 'Show', doing_item %></td>
        <td><%= link_to 'Edit', edit_doing_item_path(doing_item) %></td>
        <td><%= link_to 'Destroy', doing_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doing item', new_doing_item_path %>

doing/app/views/doing_items/new.html.erb
<h1>New Doing Item</h1>

<%= render 'form' %>

<%= link_to 'Back', doing_items_path %>

doing/app/views/doing_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @doing_item.title %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @doing_item.deadline %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @doing_item.priority %>
</p>

<p>
  <strong>Complete:</strong>
  <%= @doing_item.complete %>
</p>

<p>
  <strong>Description:</strong>
  <%= @doing_item.description %>
</p>

<%= link_to 'Edit', edit_doing_item_path(@doing_item) %> |
<%= link_to 'Back', doing_items_path %>

doing/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Doing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>